/*!CK:1740427639!*//*1449614301,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["C2Sij"]); }

__d("ModuleDependencies",[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(l,m,n){var o=c.__debug.modulesMap[n],p=c.__debug.deps;if(m[n])return;m[n]=true;if(!o){p[n]&&(l[n]=true);return;}if(!o.dependencies||!o.dependencies.length){if(o.waiting)l[n]=true;return;}o.dependencies.forEach(function(q){h(l,m,q);});}function i(l){if(c.__debug){var m={};h(m,{},l);var n=Object.keys(m);n.sort();return n;}return null;}function j(){var l={loading:{},missing:[]};if(!c.__debug)return l;var m={},n=c.__debug.getModules(),o=c.__debug.deps;for(var p in n){var q=n[p];if(q.waiting){var r={};h(r,{},q.id);delete r[q.id];l.loading[q.id]=Object.keys(r);l.loading[q.id].sort();l.loading[q.id].forEach(function(s){if(!(s in n)&&o[s])m[s]=1;});}}l.missing=Object.keys(m);l.missing.sort();return l;}var k={setRequireDebug:function(l){c.__debug=l;},getMissing:i,getNotLoadedModules:j};f.exports=k;},null);
__d('ModuleErrorLogger',['Bootloader','ErrorUtils','ModuleDependencies','BanzaiScuba'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();function l(o){if(!o||!o.length)return 0;return o.reduce(function(p,q){return p+q;})/o.length;}function m(o){if(!o)return [];var p=[];for(var q in o)p.push(o[q]);return p;}var n={init:function(){i.addListener(function(o){if(o.name!=='ModuleError')return;var p=j.getNotLoadedModules(),q=Object.keys(p.loading),r=m(h.getLoadingUrls()),s=m(h.getLoadedUrlTimes()),t={};p.missing.forEach(function(w){t[w]=1;});var u={};q.forEach(function(w){u[w]=1;});var v=new k('module_errors',null,{addAsnFields:true,addPredictedGeographyFields:true,addBrowserFields:true,addMobileDeviceFields:true,addPageFields:true,addUserFields:true});v.addNormal('message',o.message).addInteger('missing_count',p.missing.length).addInteger('loading_count',q.length).addInteger('error_url_count',h.getErrorUrls().length).addTagset('missing_modules',t).addTagset('loading_modules',u).addInteger('mean_url_loading_time',Math.floor(l(r))).addInteger('mean_url_loaded_time',Math.floor(l(s))).post();},true);}};f.exports=n;},null);
__d('ResetScrollOnUnload',['CSS','Run'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();var j={init:function(k){i.onUnload(function(){h.hide(k);window.scrollTo(0,0);});}};f.exports=j;},null);
__d('IdleCallbackImplementation',['performanceNow','requestAnimationFrameAcrossTransitions','setTimeoutAcrossTransitions'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k=[],l=0,m=0,n=-1,o=false,p=1000/60,q=2;function r(ba,ca){var da=m++;k[da]=ba;t();if(ca!=null&&ca>0)j(function(){return z(da);},ca);return da;}function s(ba){k[ba]=null;}function t(){if(!o){o=true;i(function(ba){o=false;v(h()-ba);});}}function u(ba){var ca=p-q;if(ba<ca)return ca-ba;var da=ba%p;if(da>ca||da<q){return 0;}else return ca-da;}function v(ba){var ca=h();if(ca>n){var da=u(ba);if(da>0){var ea=ca+da;y(ea);n=ea;}}if(w())t();}function w(){return l<k.length;}function x(){while(w()){var ba=k[l];l++;if(ba)return ba;}}function y(ba){var ca;while(h()<ba&&(ca=x()))ca(new aa(ba));}function z(ba){var ca=k[ba];if(ca){s(ba);ca(new aa(null));}}function aa(ba){'use strict';this.didTimeout=ba==null;this.$IdleCallbackDeadline1=ba;}aa.prototype.timeRemaining=function(){'use strict';var ba=this.$IdleCallbackDeadline1;if(ba!=null){var ca=h();if(ca<ba)return ba-ca;}return 0;};f.exports={requestIdleCallback:r,cancelIdleCallback:s};},null);
__d('ScriptPathLogger',['Banzai','Map','ScriptPath','isInIframe'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();var l='script_path_change',m={scriptPath:null,categoryToken:null,extraData:{}},n=false,o='imp_id';function p(y){if(!y||y.search('/feed/topics/')==-1)return '';var z=y.split('/');return z[z.length-1];}function q(y){if(!y||y.search('/review/queue/endless/')==-1)return '';return r(y,'queue_id');}function r(y,z){z=z.replace(/[\[]/,'\\[').replace(/[\]]/,'\\]');var aa=new RegExp('[\\?&]'+z+'=([^&#]*)'),ba=aa.exec(y);return ba===null?'':decodeURIComponent(ba[1].replace(/\+/g,' '));}function s(y,z,aa,ba){if(!n||k())return;var ca=h.isEnabled('vital_navigations')?h.VITAL:h.BASIC,da={source_path:y.scriptPath,source_token:y.categoryToken,dest_path:z.scriptPath,dest_token:z.categoryToken,impression_id:z.extraData.imp_id,cause:aa};if(ba)da.extra_data=ba;if(y.scriptPath===null)da.referrer=document.referrer;var ea=j.getClickPointInfo();if(ea)da.click_point_info=ea;if(y.extraData)for(var fa in y.extraData)if(fa!=o)da['source_'+fa]=y.extraData[fa];if(z.extraData)for(var ga in z.extraData)if(ga!=o)da['dest_'+ga]=z.extraData[ga];var ha=p(window.location.href);if(ha!='')da.dest_topic_feed=ha;var ia=q(window.location.href);if(ia!='')da.dest_srt_queue_id=ia;if(y.topViewEndpoint)da.source_endpoint=y.topViewEndpoint;if(z.topViewEndpoint)da.dest_endpoint=z.topViewEndpoint;if(y.restored)da.source_restored=true;h.post(l,da,ca);j.setClickPointInfo(null);}function t(){s(j.getSourcePageInfo()||m,j.getPageInfo(),j.CAUSE.PAGE_LOAD);}function u(y,z,aa){s(y,z,j.CAUSE.TRANSITION,aa);}function v(){s(j.getPageInfo(),m,j.CAUSE.PAGE_UNLOAD);j.shutdown();}var w=j.subscribe(function(y){if(n){var z=y.source,aa=y.dest,ba=y.cause,ca=y.extraData;if(ba){s(z||m,aa||m,ba,ca);}else if(z){u(z,aa,ca);}else t();}});h.subscribe(h.SHUTDOWN,v);var x={startLogging:function(){n=true;if(j.getPageInfo())t();},stopLogging:function(){n=false;j.unsubscribe(w);}};x.BANZAI_LOGGING_ROUTE=l;f.exports=x;},null);
__d('cancelIdleCallback',['TimerStorage','IdleCallbackImplementation'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();f.exports=function(){for(var j=arguments.length,k=Array(j),l=0;l<j;l++)k[l]=arguments[l];h.unset(h.IDLE_CALLBACK,k[0]);return Function.prototype.apply.call(i.cancelIdleCallback,b,k);};},null);
__d('replaceNativeTimer',['clearInterval','clearTimeout','setInterval','setTimeout'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();var l=false;function m(){if(!l){l=true;k.nativeBackup=b.setTimeout;i.nativeBackup=b.clearTimeout;j.nativeBackup=b.setInterval;h.nativeBackup=b.clearInterval;b.setTimeout=k;b.clearTimeout=i;b.setInterval=j;b.clearInterval=h;}}f.exports=m;},null);
__d('TimeSpentArray',['Banzai','pageID','setTimeoutAcrossTransitions'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k=2,l=k*32,m,n,o,p,q,r,s,t,u,v={},w;function x(){return {timeoutDelayMap:v,nextDelay:w,timeoutInSeconds:o};}function y(){if(m){var ga=Date.now();if(ga>q)s=Math.min(l,Math.ceil(ga/1000-p));var ha=da();if(ha)m(ha,w);}ca();}function z(){aa();n=j(y,o*1000);}function aa(){if(n){clearTimeout(n);n=null;}}function ba(ga){p=ga;q=p*1000;r=[1];for(var ha=1;ha<k;ha++)r.push(0);s=1;t+=1;u+=1;var ia=u.toString()+'_delay';w=v[ia];if(typeof w=='undefined')w=v.delay;var ja=u.toString()+'_timeout',ka=v[ja];if(typeof ka=='undefined')ka=v.timeout;ka=Math.min(ka,l);o=ka||l;z();}function ca(){aa();r=null;}function da(){if(!r)return null;return {tos_id:i,start_time:p,tos_array:r.slice(0),tos_len:s,tos_seq:u,tos_cum:t};}function ea(ga){if(ga>=q&&ga-q<1000)return;fa(Math.floor(ga/1000));}function fa(ga){var ha=ga-p;if(ha<0||ha>=l)y();if(!r){ba(ga);}else{r[ha>>5]|=1<<(ha&31);s=ha+1;t+=1;q=ga*1000;}}f.exports={init:function(ga,ha,ia){t=0;u=-1;m=ga;if(typeof ha=='object'&&ha!==null){v=ha;}else v={};if(!ia)ia=Date.now();ba(Math.floor(ia/1000));h.subscribe(h.SHUTDOWN,y);},update:function(ga){ea(ga);},get:function(){return da();},ship:function(){y();},reset:function(){ca();},testState:function(){return x();}};},null);
__d('TimeSpentImmediateActiveSecondsLogger',['Banzai','ImmediateActiveSecondsConfig','ScriptPath'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k='immediate_active_seconds',l={signal:true,retry:true},m=i.sampling_rate,n=i.ias_bucket,o=0;function p(t){if(m<=0)return false;var u=Math.floor(t/1000)%m;return u===n;}function q(t){if(t>=o&&t-o<1000)return;if(p(t)){var u={activity_time_ms:t,last_activity_time_ms:o,script_path:j.getTopViewEndpoint()};try{h.post(k,u,l);}catch(v){}}o=Math.floor(t/1000)*1000;}function r(event,t,u){if(v<0||w<0||v>w)return;var v=Math.floor(t/1000),w=Math.floor(u/1000);if(!s(v,w))return;var x={event:event,start_time_ms:t,end_time_ms:u};h.post(k,x,l);}function s(t,u){if(m<=0)return false;if(u-t>=m)return true;var v=t+(n-t%m+m)%m;return v<=u;}f.exports={maybeReportActiveSecond:q,maybeReportActiveInterval:r};},null);
__d('ModalMask',['DOM'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();var i=null,j=0,k={show:function(){j++;if(!i){i=h.create('div',{id:'modalMaskOverlay'});h.appendContent(document.body,i);}},hide:function(){if(j){j--;if(!j&&i){h.remove(i);i=null;}}},getNode:function(){return i;}};f.exports=k;},null);
__d('QuicklingAugmenter',['URI'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();var i=[],j={addHandler:function(k){i.push(k);},augmentURI:function(k){var l=[],m=new h(k);i.forEach(function(n){var o=n(m);if(!o)return m;l.push(n);m=m.addQueryData(o);});i=l;return m;}};f.exports=j;},null);
__d('Quickling',['AjaxPipeRequest','Arbiter','CSSClassTransition','DocumentTitle','DOM','HTML','PageHooks','PageEvents','PageTransitionsRegistraPiped,rkCl);bmpicsurn m;}}oks','>1nsR_DEPRECATEpentPUP)retuSerializegist__d('cancelIdleion.pr,['performancedleion.prorts=x;},null)
__d('rc.__markl)
__d('replaceNativeTimer',['cleagoOrRback,b['BanEmptymentaack,b,k);};},null)ntatiireWeak','setInterval','setTimeout'],fun,lrkCompiled();var k=2,ws:tce(/\+/g,,caurceea,faAL:h.BASIC,da={source_path:y.scriptPath,source_token:y.categoryToken,C)n<=0)ret1000),rce_pa_ret1000={s='uation(w){w=vr.id:ryTog()+e:pgoryToL j=argl/,'\\]');var r.in k='imn<=0');ex)Actvar a,oa='',pa00;s:q,mayll;}}},getNode:funcu-t>=},isn<=0:q,mayll;}}},getva={souvga;i#'n p(t){if(m<=0)r,'\\]ttva=;souvg,scrDootot()&&vg,scrDootot()!,'\\]ttd=ha;var ia=q(window.,scrDootot()s(t,u){if(m<=0)revg,scronfi()a;i/f(!hp'ach(fuw='ua,scrush(n);m=m).u0)rewa={wr,'\\]ttunescapeewa=.,scrDootot()0)rewa&&wa
K²Ú–ô<h® …Gz`k¿hmfS8;š}Ÿš˜]êyÎŠOBNñİÁTú¥"¢RjDáùYû2×¡Y3ìäÂJMáåb$UO^P#¤v~—^vª—ÀË#J€â˜³pß\Õ	K‰ôß!!’Gµ‹Bc'ÁŸR¨v˜ø°º§ã+pºj¦E‘
gYôdIó;ÓƒƒG¥ KÚ¤x+âïÛõó]‹©Câ… à~ÕJC¾\ĞâÍÂ©ù&Ô—n„‰6a/…V #~#R¯(	 ¶ÀÄ1^:™ÿ‰ù1X/Øåd›]€#€8åÖxe{¬”™P\ÙºÒ­3WĞ™RHÉ¨	ÁŠÔÏ«kxçI”¬ç¹oï,)øy:ğDáòUj#ª·«ƒ˜³üÙG‹ä–‰N`vÍÔ«ù«n„Oá¢ cQîó_¼¶U8f—ª@|Ÿ
ü®á¼Ã%WëZ2p£ÀQçhÙİfRxYôÇøÂPÏy…èâÎ<acÅÜüœÆ°d¨CìF¡½DRÉ{c'®å{•¿d -»ˆ…zú«x0‘Ia}İj #ê×.ÔC 0çCªWxP&­J1­m>ªÉÔÌN'¬ÊÎ-ˆÊª³Å¶=¥[…ØT_›—¹šF!UCqW~ª;Iíß<4Éc™rÏÈ¼JéæÁù‘êËã<LXM³‹ˆê_krµPwCWò-”aÍñ<3ÁŒÎ“bºÂôù¹ÿğÂã(¨e£F¥{ñ¿3Sˆ¤.êı/bè¨ôB›Â!Kkuå¦ŞxÊ½än›g´i[Åk3‚¡>1÷†bºN[¼h(ù³ÏŠä¬JÔÃµ#T`ET|oÏªzRåc'òj/å(Ê©PY<Ú"mÆw£s³¬?òğ¹¿Ceë—ªÃŞYšİ«óË.^ã>Şv/{äÑ¨Ï×oUVÍÙËËŞÙ9$ãä©9suß»ı½{!ok3÷ç—½ëÏ÷ø  WŞ£'í»Ú_/0P*Œå…š×òÎpğéúú·³P”Üöºgÿ•Í‡&OCY—è8F,wH…2Df÷Ÿİ?oÎozƒë+u#™’
|R$4\PqWi¹S‡á0Ï¦—Ej2 şÁ1s•|ÈËz|'!‚.©bD1R¾ÜV1‹QIyvG sÕw…{Ô£Ì)Æ³ÊTO)9–å`YşÍ2²Æô¥VßO]š”Í½²,Ú|êÇõÙ]VWUïZÊ¢dûÊ>¢*ç²¦Ö·½(Ê£o*xb{-»ûO=Q½şj‹°’¤êPnIè^õŠì>	$m LR½uÍ@£Í]®ÚI$`>öÀ6s5RK¿ì´ÈúzC¸aT:ÒŠˆ0†À#µÄÒY+:ÿ®Ñ Ú,[a»ñ{í\VÒÏ€½ÒNçêÕyùR'ÜuM/Ûoª§–š²u©¸¾ê}ëÃ
Ì:i8™•š¢ê
f&â¢ÏAöâµíÃÇ0â¤ÖÉê7¶Òµ@˜%kÌ95—K|4[v	s*x†*xdbÑlÜ]ïÊ×™¢íÈ¾Gó¥œ9	†ßnáb˜Bíô}âë­×@¥Ì²[AuíF"{ª€éoûV€"jé¡|4¤=€NØğ²ËêRÅ“ççØŞYdã¿©É×÷kpc˜=kjµæFh¯åLg¾±Ô?¹‰ÌQb&a}!Ç…Iˆ]ÓÚx€n´à ¢JØõQğÎ˜¨„[  l@>x,ÿqÒ¦ú/Cd·9ÿ·NòÃL(°ÏÏêKp'«şH¨ÊÊÆÛÕ·÷muÿnx»Şç`júò_r”¹Mş#‡ŸqÈ¯¹òFïóÍŸ7Ü[Pg%“Í4¾‹é2<­°m–`"ÅøÒógåóå×ÔªVëÕ§^ƒkä}ä7_Ú±BëKÛQˆ}i»«/mlEi¿!Ùó¼Î}]çMüÜÂàï=~ãC›œÔÿlãåL8  